//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sky_Blue_Set_Solved_042.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDonor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public long aadhar_number { get; set; }
        public long donation_amt { get; set; }
        public string premium_donor { get; set; }
    }
}
